import { TrainingData } from "./types/ClassifierTypes";

export const seedTrainingData: TrainingData[] = [
	{ description: "TESCO SUPERMARKET GROCERIES", category: "Groceries" },
	{ description: "SAINSBURYS FOOD SHOPPING", category: "Groceries" },
	{ description: "ASDA WEEKLY SHOP", category: "Groceries" },
	{ description: "MORRISONS FRESH FOOD", category: "Groceries" },
	{ description: "WAITROSE MARKET", category: "Groceries" },
	{ description: "LIDL SHOPPING", category: "Groceries" },
	{ description: "OCADO DELIVERY", category: "Groceries" },
	{ description: "ALDI FOOD", category: "Groceries" },
	{ description: "GROCERY STORE", category: "Groceries" },
	{ description: "FRESH MARKET FOOD", category: "Groceries" },
	{ description: "WHOLE FOODS MARKET", category: "Groceries" },
	{ description: "LOCAL BUTCHER SHOP", category: "Groceries" },
	{ description: "SUPERMARKET VEGETABLES", category: "Groceries" },
	{ description: "GROCERY PICKUP", category: "Groceries" },
	{ description: "BREAD MILK EGGS", category: "Groceries" },

	{ description: "BP PETROL STATION", category: "Transport" },
	{ description: "SHELL FUEL", category: "Transport" },
	{ description: "TFL TRAVEL CARD", category: "Transport" },
	{ description: "NATIONAL RAIL TICKET", category: "Transport" },
	{ description: "PETROL STATION FUEL", category: "Transport" },
	{ description: "LONDON BUS TICKET", category: "Transport" },
	{ description: "TRAIN JOURNEY", category: "Transport" },
	{ description: "MOTORWAY SERVICE STATION", category: "Transport" },
	{ description: "EASYJET FLIGHT", category: "Transport" },
	{ description: "CAR PARK CHARGE", category: "Transport" },
	{ description: "TAXI JOURNEY", category: "Transport" },
	{ description: "RAILWAY BOOKING", category: "Transport" },
	{ description: "PETROL FILL UP", category: "Transport" },
	{ description: "BUS PASS TOP UP", category: "Transport" },
	{ description: "DRIVING FUEL", category: "Transport" },

	{ description: "COSTA COFFEE", category: "Eating Out" },
	{ description: "STARBUCKS DRINK", category: "Eating Out" },
	{ description: "MCDONALD'S LUNCH", category: "Eating Out" },
	{ description: "PIZZA HUT DINNER", category: "Eating Out" },
	{ description: "SUBWAY SANDWICH", category: "Eating Out" },
	{ description: "BURGER KING MEAL", category: "Eating Out" },
	{ description: "NANDO'S DINNER", category: "Eating Out" },
	{ description: "CAFE BREAKFAST", category: "Eating Out" },
	{ description: "RESTAURANT BILL", category: "Eating Out" },
	{ description: "PUB DINNER", category: "Eating Out" },
	{ description: "CHIPOTLE MEAL", category: "Eating Out" },
	{ description: "HOTEL RESTAURANT", category: "Eating Out" },
	{ description: "LATTE AND CAKE", category: "Eating Out" },
	{ description: "DINNER TAKEAWAY", category: "Eating Out" },
	{ description: "BRUNCH CAFÉ", category: "Eating Out" },

	{ description: "AMAZON ORDER", category: "Shopping" },
	{ description: "EBAY PURCHASE", category: "Shopping" },
	{ description: "ARGOS HOME GOODS", category: "Shopping" },
	{ description: "ONLINE SHOPPING PAYMENT", category: "Shopping" },
	{ description: "JOHN LEWIS ORDER", category: "Shopping" },
	{ description: "ETSY STORE ORDER", category: "Shopping" },
	{ description: "CURRYS ELECTRICALS", category: "Shopping" },
	{ description: "ASOS CLOTHING", category: "Shopping" },
	{ description: "NEW LOOK PURCHASE", category: "Shopping" },
	{ description: "DEPARTMENT STORE SHOP", category: "Shopping" },
	{ description: "IKEA HOMEWARES", category: "Shopping" },
	{ description: "ONLINE RETAIL ORDER", category: "Shopping" },
	{ description: "GIFT SHOP PURCHASE", category: "Shopping" },
	{ description: "H&M CLOTHES", category: "Shopping" },
	{ description: "HOME SHOPPING", category: "Shopping" },

	{ description: "NETFLIX MONTHLY SUBSCRIPTION", category: "Entertainment" },
	{ description: "SPOTIFY PREMIUM", category: "Entertainment" },
	{ description: "CINEWORLD CINEMA TICKET", category: "Entertainment" },
	{ description: "DISNEY PLUS", category: "Entertainment" },
	{ description: "YOUTUBE PREMIUM", category: "Entertainment" },
	{ description: "BBC IPLAYER", category: "Entertainment" },
	{ description: "STREAMING SERVICE", category: "Entertainment" },
	{ description: "GAME STORE PURCHASE", category: "Entertainment" },
	{ description: "MUSIC SUBSCRIPTION", category: "Entertainment" },
	{ description: "LIVE CONCERT TICKET", category: "Entertainment" },
	{ description: "MOVIE TICKET", category: "Entertainment" },
	{ description: "PLAYSTATION STORE", category: "Entertainment" },
	{ description: "TV STREAMING", category: "Entertainment" },
	{ description: "LIVE SHOW TICKETS", category: "Entertainment" },
	{ description: "AUDIOBOOK SERVICE", category: "Entertainment" },

	{ description: "ELECTRICITY BILL PAYMENT", category: "Utilities" },
	{ description: "GAS SUPPLY BILL", category: "Utilities" },
	{ description: "WATER COMPANY PAYMENT", category: "Utilities" },
	{ description: "TV LICENSE", category: "Utilities" },
	{ description: "MOBILE PHONE BILL", category: "Utilities" },
	{ description: "INTERNET PROVIDER", category: "Utilities" },
	{ description: "ENERGY SUPPLY", category: "Utilities" },
	{ description: "UTILITY BILL", category: "Utilities" },
	{ description: "HOME INTERNET", category: "Utilities" },
	{ description: "TELECOM BILL", category: "Utilities" },
	{ description: "POWER BILL", category: "Utilities" },
	{ description: "HOME ENERGY", category: "Utilities" },
	{ description: "PHONE BILL PAYMENT", category: "Utilities" },
	{ description: "BROADBAND SERVICE", category: "Utilities" },
	{ description: "WATER RATE", category: "Utilities" },

	{ description: "SALARY PAYMENT", category: "Income" },
	{ description: "MONTHLY PAY", category: "Income" },
	{ description: "EMPLOYER PAYROLL", category: "Income" },
	{ description: "BONUS PAYMENT", category: "Income" },
	{ description: "WAGES DEPOSIT", category: "Income" },
	{ description: "PAYCHECK", category: "Income" },
	{ description: "COMPANY TRANSFER", category: "Income" },
	{ description: "BANK DEPOSIT", category: "Income" },
	{ description: "INTEREST PAYMENT", category: "Income" },
	{ description: "INVESTMENT RETURN", category: "Income" },
	{ description: "MONTHLY SALARY", category: "Income" },
	{ description: "WORK PAY", category: "Income" },
	{ description: "INCOME TRANSFER", category: "Income" },
	{ description: "PENSION PAYMENT", category: "Income" },
	{ description: "DIVIDEND PAYMENT", category: "Income" },

	{ description: "SAVINGS TRANSFER", category: "Savings" },
	{ description: "BANK SAVINGS ACCOUNT", category: "Savings" },
	{ description: "INVESTMENT CONTRIBUTION", category: "Savings" },
	{ description: "PENSION TRANSFER", category: "Savings" },
	{ description: "SAVINGS DEPOSIT", category: "Savings" },
	{ description: "RETIREMENT FUND", category: "Savings" },
	{ description: "EMERGENCY FUND", category: "Savings" },
	{ description: "SAVINGS ACCOUNT", category: "Savings" },
	{ description: "GOAL FUND", category: "Savings" },
	{ description: "INVESTMENT SAVINGS", category: "Savings" },
	{ description: "SAVINGS GOAL", category: "Savings" },
	{ description: "TRAVEL FUND", category: "Savings" },
	{ description: "LONG TERM SAVINGS", category: "Savings" },
	{ description: "FIXED SAVINGS", category: "Savings" },
	{ description: "EDUCATION FUND", category: "Savings" },

	{ description: "APPLE TV SUBSCRIPTION", category: "Subscriptions" },
	{ description: "GYM MEMBERSHIP", category: "Subscriptions" },
	{ description: "MAGAZINE SUBSCRIPTION", category: "Subscriptions" },
	{ description: "MONTHLY SOFTWARE", category: "Subscriptions" },
	{ description: "STREAMING MEMBERSHIP", category: "Subscriptions" },
	{ description: "HEALTH CLUB FEE", category: "Subscriptions" },
	{ description: "CLOUD STORAGE", category: "Subscriptions" },
	{ description: "VIDEO SUBSCRIPTION", category: "Subscriptions" },
	{ description: "NEWSLETTER SERVICE", category: "Subscriptions" },
	{ description: "APP SUBSCRIPTION", category: "Subscriptions" },
	{ description: "ONLINE COURSE SUBSCRIPTION", category: "Subscriptions" },
	{ description: "GYM MEMBERSHIP FEE", category: "Subscriptions" },
	{ description: "MUSIC SERVICE", category: "Subscriptions" },
	{ description: "DIGITAL SUBSCRIPTION", category: "Subscriptions" },
	{ description: "WEB HOSTING", category: "Subscriptions" },

	{ description: "MISCELLANEOUS PURCHASE", category: "Miscellaneous" },
	{ description: "HOUSEHOLD MISCELLANEOUS", category: "Miscellaneous" },
	{ description: "GENERAL SHOPPING", category: "Miscellaneous" },
	{ description: "VARIOUS CHARGES", category: "Miscellaneous" },
	{ description: "OTHER EXPENSE", category: "Miscellaneous" },
	{ description: "MISCELLANEOUS EXPENSE", category: "Miscellaneous" },
	{ description: "SMALL PURCHASE", category: "Miscellaneous" },
	{ description: "ODD JOB PAYMENT", category: "Miscellaneous" },
	{ description: "MISC ITEM PURCHASE", category: "Miscellaneous" },
	{ description: "GENERAL HOUSEHOLD COST", category: "Miscellaneous" },
	{ description: "MISCELLANEOUS FEE", category: "Miscellaneous" },
	{ description: "VARIED EXPENSES", category: "Miscellaneous" },
	{ description: "SMALL HOUSEHOLD COST", category: "Miscellaneous" },
	{ description: "UNEXPECTED CHARGE", category: "Miscellaneous" },
	{ description: "MISC COST", category: "Miscellaneous" },
];
